# Copyright (c) 2022 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/ohos.gni")
import("//build/ohos/ace/ace.gni")
import("//foundation/distributeddatamgr/kv_store/kv_store.gni")
import("//foundation/distributeddatamgr/kv_store/kv_store_deps.gni")

ohos_shared_library("cj_distributed_kv_store_ffi") {
  branch_protector_ret = "pac_ret"
  sanitize = {
    boundary_sanitize = true
    ubsan = true
    cfi = true
    cfi_cross_dso = true
    debug = false
  }

  include_dirs = [
    "${kv_store_base_path}/frameworks/common",
    "${kv_store_base_path}/frameworks/jskitsimpl/distributedkvstore/include",
    "${kv_store_base_path}/frameworks/innerkitsimpl/distributeddatafwk/include",
    "${kv_store_base_path}/frameworks/innerkitsimpl/kvdb/include",
    "${kv_store_base_path}/frameworks/cj/include",
  ]

  if (product_name != "ohos-sdk") {
    sources = [
      "../../frameworks/cj/src/distributed_kv_store_ffi.cpp",
      "../../frameworks/cj/src/distributed_kv_store_impl.cpp",
      "../../frameworks/cj/src/distributed_kv_store_utils.cpp",
    ]

    deps = [ "${kv_store_base_path}/interfaces/innerkits/distributeddata:distributeddata_inner" ]
    deps += deps_common_event_service
    deps += deps_ability_base_want
    deps += deps_ability_runtime_ability_connect_callback_stub
    deps += deps_ability_runtime_ability_manager
    deps += deps_ability_runtime_abilitykit_native
    deps += deps_ability_runtime_napi_base_context
    deps += deps_hilog
    deps += deps_ipc_single
    deps += deps_napi
    deps += deps_cj_bind_ffi
    deps += deps_cj_bind_native

    external_deps = [
      "c_utils:utils",
      "bounds_checking_function:libsec_shared",
      "json:nlohmann_json_static",
    ]
    external_deps += external_deps_common_event_service
    external_deps += external_deps_ability_base_want
    external_deps += external_deps_ability_runtime_ability_connect_callback_stub
    external_deps += external_deps_ability_runtime_ability_manager
    external_deps += external_deps_ability_runtime_abilitykit_native
    external_deps += external_deps_ability_runtime_napi_base_context
    external_deps += external_deps_napi
    external_deps += external_deps_cj_bind_ffi
    external_deps += external_deps_cj_bind_native
    external_deps += external_deps_hilog
    external_deps += external_deps_ipc_single
  } else {
    defines += [ "PREVIEWER" ]
    sources =
        [ "../../kvstoremock/frameworks/cj/distributed_kv_store_mock.cpp" ]
  }
  innerapi_tags = [ "platformsdk" ]
  subsystem_name = "distributeddatamgr"
  part_name = "kv_store"
}
